  baseurl = "https://m4ck3ngm.com/"
  title = "Mackenzie McFate"
  author = "Mackenzie McFate"
  canonifyurls = true
  paginate = 3

  theme = "hugo-theme-lean-launch-page"
  #googleAnalytics = "UA-146526628-1"
  custom_css = "local.css"

  [params]
    build = 15
    abstract = "This landing page is designed solely to provide navigation to the sites/services listed below."
    tagline = "Welcome to Mackenzie's personal server!"
    #mailchimpURL = "//my-account.mailchimp.com/my-subscriber-url"
    # Footer text
    footertext = "<a href='https://m4ck3ngm.com' target='_blank' class='footer'> <i class='fas fa-code'></i> &nbsp;&nbsp;Hugo site by Mackenzie McFate.</a>"

    twitter = "https://twitter.com/"
    facebook = "https://facebook.com/"
    # instagram = "https://instagram.com/MyNewProduct"
    # googleplus = "https://plus.google.com/+MyNewProduct"
